const Categories = [
  {
    key: "f0",
    name: "MANGO",
    description: "fresh healthy mango",
    soldBy: "Govardhan rathode chatarjee",
    price: "90",
    discount: "30",
    category: "100below",
    dis: "30above",
    type: "fruits",

    img: "https://5.imimg.com/data5/SL/DA/GLADMIN-9523458/imam-pasand-mango-fruit-500x500.jpg",
  },
  {
    key: "f1",
    name: "APPLE",
    description: "fresh healthy apple",
    soldBy: "Govardhan rathode chatarjee",
    price: "120",
    discount: "10",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOteJc35SvHf-Wmoasnx7hQe-TiCNvIUnVlw&usqp=CAU",
  },
  {
    key: "f2",
    name: "GREEN APPLE",
    description: "fresh healthy apple",
    soldBy: "Govardhan rathode chatarjee",
    price: "200",
    discount: "20",
    category: "100above",
    dis: "20above",
    type: "fruits",
    img: "https://femina.wwmindia.com/content/2021/feb/health-benefits-of-green-apples.jpg",
  },

  {
    key: "f3",
    name: "STRAW BERRY",
    description: "fresh healthy apple",
    soldBy: "Govardhan rathode chatarjee",
    price: "140",
    discount: "30",
    category: "100above",
    dis: "30above",
    type: "fruits",
    img: "https://swall.teahub.io/photos/small/19-192365_ultra-hd-fruits-hd.jpg",
  },
  {
    key: "f4",
    name: "PAPAYA",
    description: "fresh healthy orange",
    price: "40",
    soldBy: "Govardhan rathode chatarjee",
    discount: "15",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://media.istockphoto.com/photos/whole-and-half-of-ripe-papaya-fruit-with-seeds-isolated-on-white-picture-id864053288?b=1&k=20&m=864053288&s=170667a&w=0&h=IsyLu5b7vvJycnyLcQwBGv88BOXMZub_W5AyM9mvps0=",
  },
  {
    key: "f5",
    name: "PINEAPPLE",
    description: "fresh healthy pineapple",
    price: "60",
    soldBy: "kaamasani bharath reddy",
    discount: "15",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://www.thespruceeats.com/thmb/ilvEyqMbvO7dhLoFlT8-ddc0KF8=/3802x3802/smart/filters:no_upscale()/hawaii--platter-of-large-ripe-pineapples--503869977-595d304c5f9b58843f18f227.jpg",
  },
  {
    key: "f6",
    name: "BANANA",
    description: "fresh healthy banana",
    price: "40",
    soldBy: "kaamasani bharath reddy",
    discount: "10",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://media.npr.org/assets/img/2011/08/19/istock_000017061174small-6ca3bb7c8b6c768b92153932e822623a95065935.jpg",
  },

  {
    key: "f7",
    name: "ORANGE",
    description: "fresh healthy orange",
    price: "150",
    soldBy: "kaamasani bharath reddy",
    discount: "10",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://www.rd.com/wp-content/uploads/2017/12/01_oranges_Finally%E2%80%94Here%E2%80%99s-Which-%E2%80%9COrange%E2%80%9D-Came-First-the-Color-or-the-Fruit_691064353_Lucky-Business.jpg",
  },
  {
    key: "f8",
    name: "POMEGRANATE",
    description: "fresh healthy pomegranate",
    price: "200",
    soldBy: "Govardhan rathode chatarjee",
    discount: "15",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://www.vhv.rs/dpng/d/104-1049752_all-fruits-hd-png-download.png",
  },
  {
    key: "f9",
    name: "KIWI",
    description: "fresh healthy KIWI",
    price: "200",
    soldBy: "kaamasani bharath reddy",
    discount: "15",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://www.onlyfoods.net/wp-content/uploads/2012/06/Kiwi-Fruit-Images.jpg",
  },
  {
    key: "f10",
    name: "BLACK GRAPES",
    description: "fresh healthy black grapes",
    price: "200",
    soldBy: "kaamasani bharath reddy",
    discount: "15",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://2.bp.blogspot.com/-TBYmWnxLD7s/WFjUZ9Ahu3I/AAAAAAAACIQ/yZoURmPFXgQtx6_wSAGkBmC_koT9thtwgCLcB/s1600/Grapes%2BHD%2BPhoto.jpg",
  },
  {
    key: "f11",
    name: "GUAVA",
    description: "fresh healthy guava",
    price: "80",
    soldBy: "kaamasani bharath reddy",
    discount: "10",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://i.ytimg.com/vi/afJvEADf4rA/maxresdefault.jpg",
  },
  {
    key: "f12",
    name: "SAPOTA",
    description: "fresh healthy sapota",
    price: "80",
    soldBy: "rokinaldo paparao",
    discount: "10",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://blog-images.pharmeasy.in/2021/05/18144539/shutterstock_1772959055-1.jpg",
  },
  {
    key: "f13",
    name: "CHERRY",
    description: "fresh healthy cherries",
    price: "200",
    soldBy: "rokinaldo paparao",
    discount: "10",
    category: "100above",
    dis: "10above",
    type: "fruits",
    img: "https://media.istockphoto.com/photos/fresh-ripe-black-cherries-background-top-view-close-up-picture-id612524020?b=1&k=20&m=612524020&s=170667a&w=0&h=djLz1GiT44xi_uvDBN-4MgFqyFHSFpReRfoKo436K6w=",
  },
  {
    key: "f14",
    name: "GREEN GRAPES",
    description: "fresh healthy green grapes",
    price: "90",
    soldBy: "kaamasani bharath reddy",
    discount: "15",
    category: "100below",
    dis: "10above",
    type: "fruits",
    img: "https://www.seekpng.com/png/detail/8-89797_fruit-drawing-clipart-grapes-fruit-logo-set-clipart.png",
  },
  {
    key: "v1",
    name: "Tomato",
    price: "90",
    discount: "20",
    soldBy: "Bhagavadh Bharath Narayan",
    description: "Fresh healthy  organic red tomato",
    category: "100below",
    dis: "20above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/ripe-tomatoes-picture-ida0119-000144?k=20&m=a0119-000144&s=612x612&w=0&h=Oh0DbKAa72F8UbjZRsugZUPRsIWP70KnJyQPfuyt1Kk=",
  },
  {
    key: "v2",
    name: "Bitter Ground",
    price: "200",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Bitter Ground",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ42k0ETw-MA89LaM6_UwZ1xHa5_fA_2bBKZg&usqp=CAU",
  },
  {
    key: "v3",
    name: "Carrots",
    price: "110",
    discount: "15",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy ground pink carrots",
    category: "100above",
    dis: "10above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmVbvCnXAyavi5zDahid9ORFAwLb-XcdITfg&usqp=CAU",
  },
  {
    key: "v4",
    name: "brinjal",
    price: "150",
    discount: "30",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy purple brinjal",
    category: "100above",
    dis: "30above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRge0t3X4pQEGc0sBaXxi-zWe3QOldDB6CB-A&usqp=CAU",
  },
  {
    key: "v5",
    name: "Cucumber",
    price: "80",
    discount: "10",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy green cucumber",
    category: "100below",
    dis: "10above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsh_5k5dAqUr4BscUcYeNE2O9aXpgz24MidQ&usqp=CAU",
  },
  {
    key: "v6",
    name: "Lady's Finger",
    price: "120",
    discount: "10",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy green Ladys finger",
    category: "100above",
    dis: "10above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHqqVNtuL0zrMrMfiKbo5U0coxRMtSD1jzrw&usqp=CAU",
  },
  {
    key: "v7",
    name: "Carrot",
    price: "150",
    discount: "10",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Carrots",
    category: "100above",
    dis: "10above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/carrots-picture-id92026520?k=20&m=92026520&s=612x612&w=0&h=Cp3ULTpDVtm1O3abn9P_CAdA84W1QB6aPzg33-A-C5A=",
  },
  {
    key: "v8",
    name: "Green Beans",
    price: "120",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy green Beans",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://3.imimg.com/data3/KT/IE/DIR-1050803/images-img_beans-250x250.jpg",
  },
  {
    key: "v9",
    name: "Ginger",
    price: "140",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy white Ginger",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/dried-ginger-and-ground-ginger-close-up-picture-id1167521639?k=20&m=1167521639&s=612x612&w=0&h=9MHoaoTLn2nATA-2WMRZPjav56leulyIonmNx906bbw=",
  },
  {
    key: "v10",
    name: "Onions",
    price: "30",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy red Onions",
    category: "100below",
    dis: "20above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1hI5Ti5tf5OWIxPAEqNz-ZV64DjT8vB8YhwkveUe0cq-NIUebag5xD9SuNBmvB85ad_Y&usqp=CAU",
  },
  {
    key: "v11",
    name: "Green Capsicum",
    price: "150",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Green Capsicum",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/one-green-bell-pepper-isolated-on-a-plain-white-background-picture-id157476648?k=20&m=157476648&s=612x612&w=0&h=indl2MMHkryuj-65BQAte3r6c0GOg-3Og37Hdg6ZpuQ=",
  },
  {
    key: "v12",
    name: "Raddish",
    price: "200",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Raddish",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/whole-and-sliced-black-radish-and-an-old-cleaver-on-rusty-ground-picture-id932627730?k=20&m=932627730&s=612x612&w=0&h=qi9bT7SFwnm8UgiwjDTWvxGHPBKVPejKrgXVaHIx5WY=",
  },
  {
    key: "v13",
    name: "Cali Flower",
    price: "200",
    discount: "30",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Red Cali Flower",
    category: "100above",
    dis: "30above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/fresh-organic-cauliflower-cut-into-small-pieces-in-a-bowl-vegetarian-picture-id533828336?k=20&m=533828336&s=612x612&w=0&h=nGxJFcbcCn14jMCeU6gBXo8dhKCiof0_w7_PkAXOkdI=",
  },
  {
    key: "v14",
    name: "Spinach",
    price: "150",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Green Spinach",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://media.gettyimages.com/photos/fresh-spinach-leaves-in-colander-on-wood-picture-id604375571?k=20&m=604375571&s=612x612&w=0&h=K6_yeVQHn96Kt7p1MsoD_Rg9jK3UtRW-RHA_0pfEbMo=",
  },
  {
    key: "v15",
    name: "Red Capsicum",
    price: "200",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Red Capsicum",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK8-iDucrmRNmWRBEiZkIr2ZNl7cVWAapX-A&usqp=CAU",
  },
  {
    key: "v16",
    name: "Ash Guard",
    price: "300",
    discount: "20",
    soldBy: "Prabhu Kanakambaram",
    description: "Fresh healthy Red Capsicum",
    category: "100above",
    dis: "20above",
    type: "vegetables",
    img: "https://qph.fs.quoracdn.net/main-qimg-4d5d5b17f3d21a5ad4c1782f41694fa0",
  },

  {
    key: "d1",
    name: "Milk",
    price: "90",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100below",
    dis: "10above",
    type: "dairy",
    img: "https://media.gettyimages.com/photos/dairy-products-cheese-yoghurt-milk-picture-id155372492?k=20&m=155372492&s=612x612&w=0&h=Wxx6LBFxrqGYFHQ7letLwlVN7PJQA1wUzKVzxOLfUGI=",
  },
  {
    key: "d2",
    name: "Cheese",
    price: "200",
    discount: "20",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100above",
    dis: "20above",
    type: "dairy",
    img: "https://media.gettyimages.com/photos/dairy-products-shot-on-rustic-wooden-table-picture-id910881428?k=20&m=910881428&s=612x612&w=0&h=c-wO3gdyknBh8SUzwDTWCRQ9aALx0Cpb2qy8aSbqQV8=",
  },
  {
    key: "d3",
    name: "Butter",
    price: "140",
    discount: "30",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100above",
    dis: "30above",
    type: "dairy",
    img: "https://media.gettyimages.com/photos/high-angle-view-of-butter-against-white-background-picture-id1201636366?k=20&m=1201636366&s=612x612&w=0&h=XK50WVdZYc2mV1tv3ZE5mNUInoq_I-knNRgXQhRyjwI=",
  },
  {
    key: "d4",
    name: "YOGURT",
    price: "95",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100below",
    dis: "10above",
    type: "dairy",
    img: "https://media.gettyimages.com/vectors/yoghurt-with-spoon-vector-id1185514634?k=20&m=1185514634&s=612x612&w=0&h=gGlkfNEb8cxlv_Kg2RCVV_QtLHGH-8tLCmVKi3I0O2E=",
  },

  {
    key: "d5",
    name: "ICE CREAM",
    price: "140",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100above",
    dis: "10above",
    type: "dairy",
    img: "https://media.gettyimages.com/illustrations/frozen-yogurt-burst-illustration-id167590001?k=20&m=167590001&s=612x612&w=0&h=Wouq7FBU81dvxurtr-GJNi4ppgpipJKfUE3YImm-rFs=",
  },

  {
    key: "d6",
    name: "CUSTARD",
    price: "120",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100above",
    dis: "10above",
    type: "dairy",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwj-W36BWutbB2cpNk1KPp84KY5iDJSGH2xQ&usqp=CAU",
  },

  {
    key: "d7",
    name: "CASEIN",
    price: "150",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100above",
    dis: "10above",
    type: "dairy",
    img: "https://m.media-amazon.com/images/I/31o4sPvblFL._AC_UL480_FMwebp_QL65_.jpg",
  },
  {
    key: "d8",
    name: "WHIPPED CREAM",
    price: "90",
    discount: "10",
    soldBy: "Harsshath Singha Roy",
    description: "Fresh healthy butter from sterlized milk",
    category: "100below",
    dis: "10above",
    type: "dairy",
    img: "https://media.gettyimages.com/photos/high-angle-view-of-coffee-with-whipped-cream-picture-id548328073?k=20&m=548328073&s=612x612&w=0&h=SJu6ZndOmKO2YB5PbVfvcu5claQ8nvdIOMEtdZ_3eUU=",
  },

  {
    key: "p1",
    name: "Ground Nuts",
    price: "80",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " healthy organic grounds",
    category: "100below",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/background-of-argan-seeds-produced-by-argania-spinosa-tree-picture-id936757522?k=20&m=936757522&s=612x612&w=0&h=QEpI7EKVImbRf6KuK0brl8ef557Skh6Ezga2mS9vRy8=",
  },
  {
    key: "p2",
    name: "dal",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "Fresh healthy  organic dal",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://5.imimg.com/data5/NO/CQ/UR/SELLER-22139392/toor-dal-500x500.jpg",
  },
  {
    key: "p3",
    name: "Green Gram",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Green gram",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/mung-bean-in-white-background-picture-id1174571099?k=20&m=1174571099&s=612x612&w=0&h=chBMVnvlqeanj8-cQnDCqvwcbM6qC4JSAHdrkeCLsKo=",
  },
  {
    key: "p4",
    name: "Black Gram",
    price: "150",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Black gram",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlAqnNLkBGRVK2W-Fr9yYKsMayGbgZNuSvXQ&usqp=CAU",
  },
  {
    key: "p5",
    name: "Urad Dhal",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Urad Dhal",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/indian-cooking-vaal-ni-dhal-chori-beans-toover-dhal-masoor-masoor-ni-picture-id142035168?k=20&m=142035168&s=612x612&w=0&h=zFvgMY_accwt6TRnuWTl8jFI3C9kl_nfLnGhFbSq5Qo=",
  },
  {
    key: "p6",
    name: "Cashew Nuts",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Cashew Nuts",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://image.freepik.com/free-photo/raw-cashews-nuts-bag-dark-background_1150-45358.jpg",
  },
  {
    key: "p9",
    name: "Almonds",
    price: "400",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Almonds",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzHSvHBtaxJtgDLhKQJoIzoeey8LeYBu1x-A&usqp=CAU",
  },
  {
    key: "p8",
    name: "Pista",
    price: "300",
    discount: "10",
    soldBy: "Rokesh tribbiani",
    description: "Fresh healthy  organic Pista",
    category: "100above",
    dis: "10above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/two-bowls-of-gajar-ka-halwa-kept-on-a-wooden-table-picture-id1292897380?k=20&m=1292897380&s=612x612&w=0&h=2334ZSqyCKpHpBRzjSuuSCDPKsXzw6FYiyK_ZhrpQjI=",
  },
  {
    key: "p7",
    name: "Rice",
    price: "50",
    discount: "10",
    soldBy: "Rokesh tribbiani",
    description: " organic Rice",
    category: "100below",
    dis: "10above",
    type: "pulses",
    img: "https://st2.depositphotos.com/1753833/5473/i/600/depositphotos_54739737-stock-photo-rice-in-burlap-sack.jpg",
  },
  {
    key: "p9",
    name: "Wheat",
    price: "20",
    discount: "10",
    soldBy: "Rokesh tribbiani",
    description: " organic Wheat",
    category: "100below",
    dis: "10above",
    type: "pulses",
    img: "https://lh3.googleusercontent.com/proxy/3BnxfKfcujvcbNZy_Q4dOW5-Fyukb0MzDPkOc8_LDlRFles9cfU90Fc8AonpiRPovlLz3GZ7RKkIbH8jT1Cc-RIt",
  },
  {
    key: "p10",
    name: "Ragi",
    price: "70",
    discount: "10",
    soldBy: "Rokesh tribbiani",
    description: " organic Ragi",
    category: "100below",
    dis: "10above",
    type: "pulses",
    img: "https://5.imimg.com/data5/SELLER/Default/2021/2/TX/VF/BJ/9888965/finger-millet-whole-ragi-500x500.jpg",
  },
  {
    key: "p11",
    name: "Coriander Seeds",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: " organic Coriander seeds",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://5.imimg.com/data5/GG/VE/MY-324254/husk-500x500.jpg",
  },
  {
    key: "p12",
    name: "Blackpepper",
    price: "180",
    discount: "15",
    soldBy: "Rokesh tribbiani",
    description: "  organic Black pepper",
    category: "100above",
    dis: "10above",
    type: "pulses",
    img: "https://grocypie.com/wp-content/uploads/2021/01/Kali-Mirch-b.jpg",
  },
  {
    key: "p13",
    name: "Cumin Seeds",
    price: "150",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic  Cumin Seeds",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/closeup-of-caraway-seeds-in-old-spoon-on-wooden-table-picture-id743739731?k=20&m=743739731&s=612x612&w=0&h=YkutKzROUDH6-AFEFiaYiVZRMGe7ZvbyGg0Cj7c07zM=",
  },
  {
    key: "p14",
    name: "Ilachi",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic Ilachi",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/green-cardamom-pods-picture-id183384836?k=20&m=183384836&s=612x612&w=0&h=nTqoTRN35n5t8iqs_mOP_WxiXqwTWCzjWnmfaP_n7ww=",
  },
  {
    key: "p15",
    name: "Green Peas",
    price: "250",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic Green Peas",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://cf-images.us-east-1.prod.boltdns.net/v1/static/429048911/f55bf096-d38c-492d-8f40-fd2f52abf766/8c61041b-5fe0-4124-9554-d08b4cc6a61f/1920x1080/match/image.jpg",
  },
  {
    key: "p16",
    name: "Bengal Gram",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic Bengal Gram",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://img2.exportersindia.com/product_images/bc-full/2021/2/8519175/split-bengal-gram-1614249021-5735045.jpeg",
  },
  {
    key: "p17",
    name: "Kindey Beans",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic Kidney Beans",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://media.gettyimages.com/photos/closeup-of-kidney-beans-in-bowl-on-table-picture-id769810725?k=20&m=769810725&s=612x612&w=0&h=pvPOZVLrhR1X_csM0Q9LrUaB9IE3EkpCQ259UNVeQCs=",
  },
  {
    key: "p18",
    name: "Black-Eyed-Beans",
    price: "200",
    discount: "20",
    soldBy: "Rokesh tribbiani",
    description: "  organic Black-Eyed-Beans",
    category: "100above",
    dis: "20above",
    type: "pulses",
    img: "https://cpimg.tistatic.com/06440574/b/4/Black-Eyed-Beans.jpg",
  },
];
export default Categories;
