export const ADD_TO_CART="ADD_TO_CART"
export const ADD_QTY="ADD_QTY"
export const SUB_QTY="SUB_QTY"
export const REM_CART="REM_CART"
export const ADD_TO_ORDER="ADD_TO_ORDER"
export const transfer ="transfer"
